{
 "title": "Status API",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Taxa de erros",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (\r\n  rate(http_server_requests_seconds_count{job=\"claro-pedidos-backend\", status=~\"4..|5..\"}[1m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência média",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"claro-pedidos-backend\"}[1m]))\r\n/\r\nsum(rate(http_server_requests_seconds_count{job=\"claro-pedidos-backend\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Req/s por endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (method, uri, status) (\r\n  rate(http_server_requests_seconds_count{job=\"claro-pedidos-backend\"}[1m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status API",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"claro-pedidos-backend\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}